### PR TITLE
Upgrade version of marked.js to 0.3.9 (latest).

### PR DESCRIPTION
**Pull request by jonathanswenson**
cc @jbandhauer

### CODE REVIEW

**Comment by jbandhauer** [comment]
I don't have any particular thoughts on this. Have you audited the change in that package to confirm that is doesn't have any unanticipated effects? Have you confirmed that it works well with the content that we display in our product?

cc @dthorpe

**Comment by jbandhauer** [comment]
..oh, shoot, now I'm actually looking at the change. You are changing 'generated' files. That is not the way to make changes here.

**Comment by jonathanswenson** [comment]
Ah the change needs to go in the marked.js file in lib (instead of dist). Probably need to read a readme somewhere...

**Comment by jbandhauer** [comment]
... then you *also* need to cause the dist to regen so that dist is always up to date.

**Comment by jonathanswenson** [comment]
Yeah because I had already updated the dist file, the generation of the assets with `npm run-script build` didn't cause any further changes.

**Comment by jonathanswenson** [comment]
Pulled in the new changes and everything seems 👍

**Pull request merged**
